### PR TITLE
setup.sh: add `bind`, `unbind`, `device-driver` and `disk-status` commands for a single device

### PR DESCRIPTION
**Pull request by derekbit**
#### Which issue(s) this PR fixes:

Issue Longhorn/longhorn#7672

#### What this PR does / why we need it:

- bind: bind a block device to an userspace IO driver 
- unbind: unbind a block device from an userspace IO driver and rebind to a kernel driver
- device-driver: get the kernel driver used for the given block driver
- disk-status: get disk status

### CODE REVIEW

**Comment by DamiaSan** [comment]
Could you explain better the purpose of this development? Is is something similar to the RPC command `bdev_nvme_attach_controller`?

**Comment by derekbit** [comment]
As the title and the examples said, the commands are using for binging and unbinding a block device to a uio driver.

Please see https://github.com/spdk/spdk/blob/master/README.md#huge for more information.

**Comment by DamiaSan** [comment]
> As the title and the examples said, the commands are using for binging and unbinding a block device to a uio driver.
> 
> Please see https://github.com/spdk/spdk/blob/master/README.md#huge for more information.

In this way you are telling the script which device to bind/unbind right? Because it would unbind from the kernel driver all unmounted nvme devices found.

**Comment by derekbit** [comment]
> > As the title and the examples said, the commands are using for binging and unbinding a block device to a uio driver.
> > Please see https://github.com/spdk/spdk/blob/master/README.md#huge for more information.
> 
> In this way you are telling the script which device to bind/unbind right? Because it would unbind from the kernel driver all unmounted nvme devices found.

You are right!

**Review by DamiaSan — APPROVED** [review]

**Pull request merged**
