### PR TITLE
raid1 bdev: support unmap operation

### PR DESCRIPTION
**Pull request by derekbit**
#### Which issue(s) this PR fixes:

Issue longhorn/longhorn#7925

### CODE REVIEW

**Review by shuo-wu — APPROVED** [review]
LGTM
Does this mean that the main part of RAID unmap operation (`raid_bdev_unmap_blocks`) is already implemented by upstream? Why don't they directly implement the rest?

**Comment by derekbit** [comment]
> LGTM Does this mean that the main part of RAID unmap operation (`raid_bdev_unmap_blocks`) is already implemented by upstream? Why don't they directly implement the rest?

I think `raid_bdev_unmap_blocks` only handles the specified base bdev and io channel rather than all base bdevs.

**Comment by DamiaSan** [comment]
What about the modification to `setup.sh`, don't we have another PR? https://github.com/longhorn/spdk/pull/27

**Review by DamiaSan — CHANGES_REQUESTED** [review]
What about the modification to setup.sh, don't we have another PR? https://github.com/longhorn/spdk/pull/27

**Comment by derekbit** [comment]
> What about the modification to setup.sh, don't we have another PR? #27

We need to merge https://github.com/longhorn/spdk/pull/27 first and rebase the PR.

**Review by DamiaSan — APPROVED** [review]

**Pull request merged**
