### PR TITLE
Longhorn v24.09

### PR DESCRIPTION
**Pull request by DamiaSan**
#### Which issue(s) this PR fixes:
Issue longhorn/longhorn#9700

#### What this PR does / why we need it:

New branch based on SPDK 24.09 release

### CODE REVIEW

**Comment by innobead** [comment]
> #### Which issue(s) this PR fixes:
> Issue [longhorn/longhorn#9700](https://github.com/longhorn/longhorn/issues/9700)

@DamiaSan please also remember to add a reference link to the source issue instead of the issue number only, so we can clearly understand what ongoing PRs are.

**Comment by derekbit** [comment]
@DamiaSan Is the lvstore creation stuck issue resolved?

**Comment by DamiaSan** [comment]
> @DamiaSan Is the lvstore creation stuck issue resolved?

Yes, I have simply [disabled](https://github.com/longhorn/spdk/pull/37/commits/d54a83da3a90252f608d4d13a899ce9c11ec0efe) the commit which cause the issue.

**Comment by derekbit** [comment]
> > @DamiaSan Is the lvstore creation stuck issue resolved?
> 
> Yes, I have simply [disabled](https://github.com/longhorn/spdk/pull/37/commits/d54a83da3a90252f608d4d13a899ce9c11ec0efe) the commit which cause the issue.

I see, but what's the original purpose of adding the flag RWF_NOWAIT`?
Any side effect if we disable it?

**Comment by DamiaSan** [comment]
It is a new feature introduced with this [commit](https://github.com/longhorn/spdk/commit/4c446029ae769fe7054d0631dea64b31a84ff7bb). After this, with another [commit](https://github.com/longhorn/spdk/pull/37/commits/c86b48a179d463c5450e0b796df81f97c7b41aee), they disabled the functionality where it is not supported. I have simply disdabled it until we are not able to understand the problem and fix it, there shouldn't be any side effects because until Septermber the functionality was not present in code base and it is disabled in environment where it is not supported.

**Review by derekbit — APPROVED** [review]

**Comment by derekbit** [comment]
@DamiaSan I have marked the longhorn-v24.09 as the default branch. Then, you can create PRs for updating the dependency in go-spdk-helper, longhorn-spdk-helper and longhorn-instance-manager.

**Comment by DamiaSan** [comment]
> @DamiaSan I have marked the longhorn-v24.09 as the default branch. Then, you can create PRs for updating the dependency in go-spdk-helper, longhorn-spdk-helper and longhorn-instance-manager.

For `go-spdk-helper` and `longhorn-spdk-engine`, the updates are in the PRs for the delta bitmap: https://github.com/longhorn/go-spdk-helper/pull/163 and https://github.com/longhorn/longhorn-spdk-engine/pull/238. Now that the new branch has been merged I will convert these drafts into real PRS.
Ok for `longhorn-instance-manager`.

**Comment by derekbit** [comment]
> > @DamiaSan I have marked the longhorn-v24.09 as the default branch. Then, you can create PRs for updating the dependency in go-spdk-helper, longhorn-spdk-helper and longhorn-instance-manager.
> 
> For `go-spdk-helper` and `longhorn-spdk-engine`, the updates are in the PRs for the delta bitmap: [longhorn/go-spdk-helper#163](https://github.com/longhorn/go-spdk-helper/pull/163) and [longhorn/longhorn-spdk-engine#238](https://github.com/longhorn/longhorn-spdk-engine/pull/238). Now that the new branch has been merged I will convert these drafts into real PRS. Ok for `longhorn-instance-manager`.

Could you separate the PRs? Create separate PRs for the spdk dependency update.

**Comment by DamiaSan** [comment]
> Could you separate the PRs? Create separate PRs for the spdk dependency update

Sure that I can, but what is the benefit? In each PR there are separate commits, one for the dependency update and one for the delta bitmap.

**Comment by derekbit** [comment]
> > Could you separate the PRs? Create separate PRs for the spdk dependency update
> 
> Sure that I can, but what is the benefit? In each PR there are separate commits, one for the dependency update and one for the delta bitmap.

It is helpful when we need to check the context of the PR and its ticket. The two commits serve for different and individual purposes, so I suggest separating them. 

The spdk update PR should belong to https://github.com/longhorn/longhorn/issues/9700.

**Comment by DamiaSan** [comment]
Ok, I will separate them.
However I suggest to not keep under review a PR for about 4 months, as for [this one](https://github.com/longhorn/spdk/pull/36), because this is the root cause of such a complication.

**Comment by derekbit** [comment]
> I suggest to not keep under review a PR for about 4 months, as for [this one](https://github.com/longhorn/spdk/pull/36), because this is the root cause of such a complication.

Yes, everyone's bandwidth has been very tight in recent months. Please ping other members if the PR is urgent.

**Pull request merged**
