### PR TITLE
Update SPDK_LVOL_NAME_MAX and SPDK_LVS_NAME_MAX to 256

### PR DESCRIPTION
**Pull request by derekbit**
Longhorn/longhorn#6067
Longhorn/longhorn#6071

### CODE REVIEW

**Review by innobead — APPROVED** [review]
LGTM

**Comment by innobead** [comment]
@DamiaSan WDYT

**Comment by DamiaSan** [comment]
It should be ok, but to be sure we would create name so long to see if these longer info are correctly saved on disk

**Comment by derekbit** [comment]
@DamiaSan 
I've verified the ticket, but I'm not sure if there is any concern from upstream maintainers' perspective. 
Can you help check it with the maintainers? If it is ok, we can submit the change to upstream.
Thank you.

**Comment by innobead** [comment]
Merged first, see if we need to change later as per the upstream feedback.

**Comment by DamiaSan** [comment]
Just posted in spdk slack channel, let's see the response

**Pull request merged**
