### PR TITLE
Snapshot checksum APIs

### PR DESCRIPTION
**Pull request by DamiaSan**
#### Which issue(s) this PR fixes:

Issue #8666

### CODE REVIEW

**Comment by derekbit** [comment]
Need to update go-spdk-helper as well.

**Review by shuo-wu — COMMENTED** [review]
I have one question: 
After deleting a parent snapshot, IIUC, its clusters should be squashed into the child snapshot. Then, do we need to manually re-calculate the child snapshot checksum?

Also, is this API a sync call? If YES, I am worried that calculating a huge snapshot will block the caller for a long time.

**Comment by DamiaSan** [comment]
> I have one question: After deleting a parent snapshot, IIUC, its clusters should be squashed into the child snapshot. Then, do we need to manually re-calculate the child snapshot checksum?

Yes, but if the child snapshot has already a checksum stored, actually we would get an error. What we could do is to add a force option to overwrite the old checksum.

> Also, is this API a sync call? If YES, I am worried that calculating a huge snapshot will block the caller for a long time.

Yes, it is a sync call. We could make it async, and to test the end of the operation we can use the RPC to retrieve the checksum: until the calculation is not ended, we would get an error of xattr not present.

**Comment by shuo-wu** [comment]
> but if the child snapshot has already a checksum stored, actually we would get an error. 

Which code guarantees this kind of validity of the snapshot checksum? 

> We could make it async

Do you mean that the caller can open a separate thread to call this API then retrieve if the checksum presents or not?

**Comment by DamiaSan** [comment]
> Which code guarantees this kind of validity of the snapshot checksum?

Actually no code guarantee the validity of snapshot's checksum. What I mean is that if a snapshot has already the snapshot checksum xattr and we try to calculate again the checksum we will get an error.

> Do you mean that the caller can open a separate thread to call this API then retrieve if the checksum presents or not?

Exactly

**Comment by shuo-wu** [comment]
> What I mean is that if a snapshot has already the snapshot checksum xattr and we try to calculate again the checksum we will get an error.

Then we need a way to handle this case. Otherwise, this feature may be meaningless, as we cannot prevent users from deleting snapshots hence we never know the snapshot checksum recorded in xattrs is still valid or not. 

WDYT? @derekbit @innobead

**Comment by DamiaSan** [comment]
> What we could do is to add a force option to overwrite the old checksum.

A possible solution.

**Comment by shuo-wu** [comment]
> > What we could do is to add a force option to overwrite the old checksum.

> A possible solution.

Will you implement it in this PR?

**Comment by DamiaSan** [comment]
> > > What we could do is to add a force option to overwrite the old checksum.
> 
> > A possible solution.
> 
> Will you implement it in this PR?

Yes, it will the first thing to do after the HackWeek.

**Comment by DamiaSan** [comment]
> Yes, it is a sync call. We could make it async, and to test the end of the operation we can use the RPC to retrieve the checksum: until the calculation is not ended, we would get an error of xattr not present.

@shuo-wu  Do you want this enhancement in this PR too?

**Comment by DamiaSan** [comment]
Anyway I will create a new PR to be merged in the new `longhorn-v24.09` branch.

**Comment by DamiaSan** [comment]
Going to create a new PR for the new branch `longhorn-v24.09`

**Comment by DamiaSan** [comment]
Created the new PR https://github.com/longhorn/spdk/pull/38

**Pull request closed without merging**
